/*
 * This file is generated by jOOQ.
*/
package demo.jooq.domain;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import demo.jooq.domain.tables.Comments;
import demo.jooq.domain.tables.Posts;
import demo.jooq.domain.tables.records.CommentsRecord;
import demo.jooq.domain.tables.records.PostsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CommentsRecord, Integer> IDENTITY_COMMENTS = Identities0.IDENTITY_COMMENTS;
    public static final Identity<PostsRecord, Integer> IDENTITY_POSTS = Identities0.IDENTITY_POSTS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CommentsRecord> CONSTRAINT_A = UniqueKeys0.CONSTRAINT_A;
    public static final UniqueKey<PostsRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CommentsRecord, PostsRecord> CONSTRAINT_AB = ForeignKeys0.CONSTRAINT_AB;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CommentsRecord, Integer> IDENTITY_COMMENTS = Internal.createIdentity(Comments.COMMENTS, Comments.COMMENTS.ID);
        public static Identity<PostsRecord, Integer> IDENTITY_POSTS = Internal.createIdentity(Posts.POSTS, Posts.POSTS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CommentsRecord> CONSTRAINT_A = Internal.createUniqueKey(Comments.COMMENTS, "CONSTRAINT_A", Comments.COMMENTS.ID);
        public static final UniqueKey<PostsRecord> CONSTRAINT_4 = Internal.createUniqueKey(Posts.POSTS, "CONSTRAINT_4", Posts.POSTS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CommentsRecord, PostsRecord> CONSTRAINT_AB = Internal.createForeignKey(demo.jooq.domain.Keys.CONSTRAINT_4, Comments.COMMENTS, "CONSTRAINT_AB", Comments.COMMENTS.POST_ID);
    }
}
