/*
 * This file is generated by jOOQ.
*/
package demo.jooq.domain;


import javax.annotation.Generated;

import demo.jooq.domain.tables.Comments;
import demo.jooq.domain.tables.Posts;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.COMMENTS</code>.
     */
    public static final Comments COMMENTS = demo.jooq.domain.tables.Comments.COMMENTS;

    /**
     * The table <code>PUBLIC.POSTS</code>.
     */
    public static final Posts POSTS = demo.jooq.domain.tables.Posts.POSTS;
}
